### ISSUE TITLE
Attribute states not generated or not assigned correctly

### ISSUE THREAD

**Issue by phantomski77** [jlamendo/ha-sensor.owlet#10]
Hi,

first of all - thank you for your great work making the Owlet finally available for Home Assistant. Much appreciated!

I own the Owlet Smart Sock 3.

Few issues regarding the alert states and/or attribute readings:
- `LOW_INTEG_READ` - when the sock is removed, owlet app produces the notification `Difficulty getting reading`, the base station starts playing music and flashing yellow. This attribute doesn't change state however. It only changes to `true` when the sock is put into base station for charging.
- `base_station_on` - when sock is charging, produces `null`, when the sock is on and active, produces `1` - shouldn't this be more *base station* connectivity, rather than *sock* connectivity (which is provided by `active` attribute)?

Thanks.

**Comment by jlamendo** [comment]
Yeah I experienced this too - the names of the attributes come straight from Owlet though, and I don't have any insight into what the conditions are for triggering them outside of what the attribute names are, as their API is entirely undocumented.
