### ISSUE TITLE
Does this still work in the latest releases 2022.5 +

### ISSUE THREAD

**Issue by Bruskey** [jlamendo/ha-sensor.owlet#16]
I have recently tried setting this up but im not getting any data coming through to any of the sensors. Is this still working in release 2022.5 as there are a few people logging issues here saying the same thing and having to downgrade back to previous version of HA to make this work?

**Comment by jlamendo** [comment]
It should be working now :)

**Comment by jlamendo** [comment]
Please reopen if you are still having issues with the latest version.
