### ISSUE TITLE
HACS Integration

### ISSUE THREAD

**Issue by gregoryduckworth** [jlamendo/ha-sensor.owlet#2]
Would it be possible to update the repo to allow installation through HACS?

**Comment by jlamendo** [comment]
It may be possible - I haven't done any development for HACS yet and I'm not sure if they have the same kinds of stringent requirements that HA core has, but I'll look into it.

**Comment by jlamendo** [comment]
Closed by https://github.com/jlamendo/ha-sensor.owlet/pull/3 - thanks for the suggestion. Readme has been updated with a new HACS install option.

**Comment by gregoryduckworth** [comment]
Amazing work! Thank you!
