### ISSUE TITLE
Owlet: Seems to be working, but logs are littered with errors

### ISSUE THREAD

**Issue by npawelek** [jlamendo/ha-sensor.owlet#20]
I've recently integrated an Owlet Dream Sock and seem to be getting entity data for all the things that matter. One odd piece is that there are a ton of errors in the Home Assistant logs with a gigantic dictionary of data. Approximately 100 errors have been reported in 20-minutes. Is normal or expected? Wondering if I can just squelch these.

Here's a sanitized version of the log for reference: https://gist.github.com/npawelek/7b54cdb73deb66eee0e6d50e52c3ec95

**Comment by cvocvo** [comment]
I'm seeing the same thing here; were you able to solve this?

Example:
Entity shows up:
![image](https://github.com/jlamendo/ha-sensor.owlet/assets/355711/4032a33b-a000-4340-bef3-56396aacb4d0)

![image](https://github.com/jlamendo/ha-sensor.owlet/assets/355711/c18e1776-e143-4d85-b2d7-611deaebf399)

Edit: it does work once you pull the sock off the charger
![image](https://github.com/jlamendo/ha-sensor.owlet/assets/355711/f047c1dd-9625-4677-ba8c-f229522081ca)

**Comment by peaster** [comment]
+1 for changing the logging level on this. It's really cluttering up my logs

**Comment by jlamendo** [comment]
Log level changes are merged
