### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by aelg305** [jlamendo/ha-sensor.owlet#24]
**Issue:** able to install from HACS, however, it would show as Disconnect!

**Running:**

- Windows HyperV
- Home Assistant 2023.2.4
- Supervisor 2023.01.1
- Operating System 9.5
- Frontend 20230202.0 - latest

I DO have adguard installed and I had turned off, unblock any and all links for HASS, ownletcare, aylanetworks.com....completely turn itoff/disable it...... even removed it all together from the network....with no succes!

**My sensor.yaml:** (dont mind the syntax...I wasnt able to get it to format properly)
`
 - platform: owlet
     username: "example@email.com"
     password: "PasswordWithNumbers&symbols"
     region: "world"`

**LOGS x103 times.... I masked key#, app_id#, etc..:**

`OWLET: [{"property": {"type": "Property", "name": "ALRT_PAUSE_CMD", "base_type": "string", "read_only": false, "direction": "input", "scope": "user", "data_updated_at": "2022-06-18T04:44:47Z", "key": xxxx, "device_key": xxxxxx, "product_name": "xxxxxxx", "track_only_changes": true, "display_name": "Alert Pause Command", "host_sw_version": false, "time_series": false, "derived": false, "app_type": null, "recipe": null, "value": "{\"ts\":xxxx}", "generated_from": null, "generated_at": null, "denied_roles": [], "ack_enabled": false, "retention_days": 30, "ack_status": null, "ack_message": null, "acked_at": null}}, {"property": {"type": "Property", "name": "APP_ACTIVE", "base_type": "boolean", "read_only": false, "direction": "input", "scope": "user", "data_updated_at": "2023-02-13T21:05:56Z", "key": xxxxx, "device_key": xxxx, "product_name": "xxxxxx", "track_only_changes": false, "display_name": "App Active", "host_sw_version": false, "time_series": false, "derived": false, "app_type": null, "recipe": null, "value": 1, "generated_from": null, "generated_at": null, "denied_roles": [], "ack_enabled": false, "retention_days": 30, "ack_status": null, "ack_message": null, "acked_at": null}}, {"property": {"type": "Property", "name": "BASE_ERROR_LOG_FILE", "base_type": "file", "read_only": true, "direction": "output", "scope": "user", "data_updated_at": "null", "key": xxxxxxxx, "device_key": xxxxxx, "product_name": "xxxxx", "track_only_c
.
.
.
.
"track_only_changes": false, "display_name": "Vitals Log File", "host_sw_version": false, "time_series": false, "derived": false, "app_type": null, "recipe": null, "value": "https://ads-owlue1.aylanetworks.com/apiv1/devices/xxxxxx/properties/VITALS_LOG_FILE/datapoints/xxxxx-606d-11ed-0ffb-xxxxxxx.json", "generated_from": null, "generated_at": null, "denied_roles": [], "ack_enabled": false, "retention_days": 30}}]`

**Comment by kyle4269** [comment]
Mine displays the same error. But I'm able to connect and see the stats within HA..

**Comment by aelg305** [comment]
I figured what my error was. I have adguard installed..... I needed to whitelist the following domains:
sdk.split.io
I also added: split.io...to ensure all its subdomains would work!
Weird
