### ISSUE TITLE
WHat does Movement Sensor mean?

### ISSUE THREAD

**Issue by cloudbr34k84** [jlamendo/ha-sensor.owlet#26]
How is this calculated as in the app you don't have access to this, it only says if the baby is moving.

So what does the movement sensor mean, is the number of leg movements per second, or hour or what??

**Comment by kguy18** [comment]
According to the app "proprietary algorithms" - the number can go over 100 if you shake the foot pretty fast, so I am sure its just a read from the accelerometer, that said they don't have any official documentation about how it is calculated.

**Comment by cloudbr34k84** [comment]
> According to the app "proprietary algorithms" - the number can go over 100 if you shake the foot pretty fast, so I am sure its just a read from the accelerometer, that said they don't have any official documentation about how it is calculated.

ok cool, good to know, cheers
