### ISSUE TITLE
Not working? United kingdom

### ISSUE THREAD

**Issue by rdbarry** [jlamendo/ha-sensor.owlet#29]
HA seems to be having trouble loading the int, error log pointing towards templates?

Logger: homeassistant.helpers.event
Source: helpers/template.py:570
First occurred: 4:54:42 PM (6 occurrences)
Last logged: 4:54:42 PM

Error while processing template: Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.heart_rate}}) renders=2>
Error while processing template: Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.oxygen_saturation}}) renders=2>
Error while processing template: Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.movement}}) renders=2>
Error while processing template: Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.battery}}) renders=2>
Error while processing template: Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.ble_rssi}}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2196, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2228, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'

Logger: homeassistant.helpers.template
Source: helpers/template.py:2209
First occurred: 4:54:42 PM (12 occurrences)
Last logged: 4:54:42 PM

Template variable error: 'None' has no attribute 'attributes' when rendering '{{states.sensor.owlet_smart_sock_ac000w016676179.attributes.heart_rate}}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{states.sensor.owlet_smart_sock_ac000w016676179.attributes.oxygen_saturation}}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{states.sensor.owlet_smart_sock_ac000w016676179.attributes.movement}}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{states.sensor.owlet_smart_sock_ac000w016676179.attributes.battery}}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{states.sensor.owlet_smart_sock_ac000w016676179.attributes.ble_rssi}}'

Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:194
Integration: Template (documentation, issues)
First occurred: 4:54:42 PM (6 occurrences)
Last logged: 4:54:42 PM

TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.oxygen_saturation}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.owlet_spo2'
TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.movement}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.owlet_movement'
TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.battery}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.owlet_battery'
TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.ble_rssi}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.owlet_rssi'
TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{states.sensor.owlet_smart_sock_ac000w016676179.attributes.ble_rssi}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.owlet_monitoring_status'

**Comment by jlamendo** [comment]
It looks like you need to update the ID of the sock in your templates to be the ID of your actual sock. ac000w016676179 for example should be swapped out.
