### ISSUE TITLE
Logging is too heavy

### ISSUE THREAD

**Issue by AlexShubovich** [jlamendo/ha-sensor.owlet#31]
Its not really an issue but in month it ate around 50gb of storage space due to logging the JSON response.
My whole system ran out of space and froze, now I'm better at configuring docker machines so the logs are rolling and this wont be a problem anymore, Nevertheless a big chunck of logs is taken by this so not a lot of logs is saved for the HA.

**Comment by jlamendo** [comment]
Thanks Alex, yeah this was just left over cruft from development. I've merged the PR that fixed this.
